"""
Standardized messaging format using MessagePack as the binary serialization format.

https://msgpack.org/
"""
from dataclasses import dataclass
from typing import Self, Protocol

import msgpack  # type: ignore
from ulid import ULID


class MessageId(ULID):
    """
    Unique message ID
    """


class MessageType(ULID):
    """
    Message type ID
    """


MessageData = bytes


@dataclass(slots=True)
class Message:
    """
    Message

    :field:`id` - unique message ID
    :field:`type` - message type
    :field:`data` - msgpack serialization format
    """

    msg_id: MessageId
    msg_type: MessageType
    data: MessageData

    @classmethod
    def create(cls, msg_type: MessageType, data: bytes) -> Self:
        """
        Constructs a new Message with an autogenerated message ID
        """
        return cls(
            msg_id=MessageId(),
            msg_type=msg_type,
            data=data,
        )

    @classmethod
    def unpack(cls, packed: bytes) -> Self:
        """
        deserializes the message
        """
        (msg_id, msg_type, data) = msgpack.unpackb(packed, use_list=False)
        return cls(
            msg_id=MessageId.from_bytes(msg_id),
            msg_type=MessageType.from_bytes(msg_type),
            data=data,
        )

    def pack(self) -> bytes:
        """
        Serialize the message

        Notes
        -----
        - serialized message format: (MessageId, MessageType, MessageData)
        """
        return msgpack.packb((self.msg_id.bytes, self.msg_type.bytes, self.data))


class Serializable(Protocol):
    """
    Serializable protocol
    """

    @staticmethod
    def message_type() -> MessageType:
        ...

    def pack(self) -> bytes:
        """
        Packs the object into bytes
        """
        ...

    @classmethod
    def unpack(cls, packed: bytes) -> Self:
        """
        Unpacks the packed bytes into a new instance of Self
        """
        ...
